target_file: master.xlsx
log: 'log.txt'
fields:
- source_name: 'First'
  casing: 'proper'
- source_name: 'Last'
  casing: 'proper'
- source_name: 'State'
  target_name: tags
  casing: 'upper'
  in_list: states.yml
- source_name: 'Email'
- source_name:
  field_number: 18
  split_by: ': '
  split:
  - index: 2
    expand_on: 'Email'
    target_name: "Alternate E-mail"
- source_name:
  field_number: 16
  casing: 'lower'
  split_by: ': '
  split:
  - index: 2
    target_name: grade level
  replace:
  - from: 'Early Childhood Educator'
    to: 'prek'
  - from: 'Kindergarten'
    to: 'kinder'
  - from: 'Grade One'
    to: 'grade 1'
  - from: 'Grade Two'
    to: 'grade 2'
  - from: 'Grade Three'
    to: 'grade 3'
  - from: 'Grade Four'
    to: 'grade 4'
  - from: 'Grade Five'
    to: 'grade 5'
  - from: 'Grade Six'
    to: 'grade 6'
  - from: 'Math Educator'
    to: 'other'
  - from: 'Social Studies Educator'
    to: 'unknown'
  - from: 'Elementary ESL'
    to: 'esl'
  - from: 'Elementary Reading Teacher'
    to: 'reading'
  - from: 'Elementary Special Education'
    to: 'sped'
  - from: 'Middle School'
    to: 'ms'
  - from: 'High School'
    to: 'hs'
- target_name: 'company'
  default_value: 'customer'
- target_name: 'Extra Field 1'
  default_value: 'customer'
- source_name: 'job title'
  default_value: '2024'
ordered_headers:
  - First
  - Last
  - tags
  - Email
  - grade level
  - company
  - Extra Field 1
  - job title
max_target_file_size: 500