type: 'ES'
target_file: 'master.csv'
log: 'log.txt'
fields: 
# - source_name: 'PERS_NAME'
#   split_by: ' '
#   split:
#   - index: 2
#     target_name: 'first'
#   - index: 3
#     target_name: 'last'
- source_name: 'FIRST_NAME'
  target_name: 'first'
- source_name: 'LAST_NAME'
  target_name: 'last'
- source_name: 'PERS_EMAIL'
  target_name: e-mail - work
- source_name: 'TITLE1'
  target_name: grade level
  replace:
  - from: 'Early Childhood Educator'
    to: 'prek'
  - from: 'Kindergarten Teacher'
    to: 'kinder'
  - from: '1st Grade Teacher'
    to: 'grade 1'
  - from: '2nd Grade Teacher'
    to: 'grade 2'
  - from: '3rd Grade Teacher'
    to: 'grade 3'
  - from: '4th Grade Teacher'
    to: 'grade 4'
  - from: '5th Grade Teacher'
    to: 'grade 5'
  - from: '6th Grade Teacher'
    to: 'grade 6'
  - from: 'Special Needs Educator'
    to: 'sped'
  - from: 'Math Educator'
    to: 'unknown'
  - from: 'Social Studies Educator'
    to: 'unknown'
  - from: 'Elementary Teacher'
    to: 'unknown'
  - from: 'Language Arts Educator'
    to: 'reading'
- source_name: 'P_STATE'
  secondary_source_name: 'STATE'
  target_name: 'tag'
- source_name: 'MANAGER'
  target_name: 'lead'
- source_name: 'I_SHORT_NM'
  secondary_source_name: 'filename' # new field
  target_name: 'school'
- target_name: 'lead'
  default_value: 'mch' #new field. Only works if there is no source_name field.
max_target_file_size: 500